name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Python (Lambda)
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Node (Frontend)
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Build Frontend
        run: |
          cd cloudguard360-dashboard
          npm install
          npm run build || true

      # Terraform
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Validate
        run: |
          cd aws/Terraform
          terraform init -input=false
          terraform validate
