name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Python (Lambda)
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - run: |
        pip install --upgrade pip
        [ -f requirements.txt ] && pip install -r requirements.txt

    # Node (Frontend)
    - uses: actions/setup-node@v3
      with:
        node-version: "18"

    - run: |
        cd cloudguard360-dashboard
        npm install
        npm run build || true

    # Terraform
    - uses: hashicorp/setup-terraform@v3

    - run: |
        cd aws/Terraform
        terraform init -input=false
        terraform validate
